/* 
 * Workforce Optimisation API
 *
 * Solver engine for solving workforce optimisation problems
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@solvice.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DemandShift
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DemandShiftTests
    {
        // TODO uncomment below to declare an instance variable for DemandShift
        //private DemandShift instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DemandShift
            //instance = new DemandShift();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DemandShift
        /// </summary>
        [Test]
        public void DemandShiftInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DemandShift
            //Assert.IsInstanceOfType<DemandShift> (instance, "variable 'instance' is a DemandShift");
        }


        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

    }

}
