/* 
 * Workforce Optimisation API
 *
 * Solver engine for solving workforce optimisation problems
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@solvice.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Demand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DemandTests
    {
        // TODO uncomment below to declare an instance variable for Demand
        //private Demand instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Demand
            //instance = new Demand();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Demand
        /// </summary>
        [Test]
        public void DemandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Demand
            //Assert.IsInstanceOfType<Demand> (instance, "variable 'instance' is a Demand");
        }


        /// <summary>
        /// Test the property 'Shift'
        /// </summary>
        [Test]
        public void ShiftTest()
        {
            // TODO unit test for the property 'Shift'
        }
        /// <summary>
        /// Test the property 'Skill'
        /// </summary>
        [Test]
        public void SkillTest()
        {
            // TODO unit test for the property 'Skill'
        }
        /// <summary>
        /// Test the property 'PrefDemand'
        /// </summary>
        [Test]
        public void PrefDemandTest()
        {
            // TODO unit test for the property 'PrefDemand'
        }

    }

}
