/* 
 * Workforce Optimisation API
 *
 * Solver engine for solving workforce optimisation problems
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@solvice.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Employee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmployeeTests
    {
        // TODO uncomment below to declare an instance variable for Employee
        //private Employee instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Employee
            //instance = new Employee();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Employee
        /// </summary>
        [Test]
        public void EmployeeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Employee
            //Assert.IsInstanceOfType<Employee> (instance, "variable 'instance' is a Employee");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Statute'
        /// </summary>
        [Test]
        public void StatuteTest()
        {
            // TODO unit test for the property 'Statute'
        }
        /// <summary>
        /// Test the property 'Skill'
        /// </summary>
        [Test]
        public void SkillTest()
        {
            // TODO unit test for the property 'Skill'
        }
        /// <summary>
        /// Test the property 'Efficiency'
        /// </summary>
        [Test]
        public void EfficiencyTest()
        {
            // TODO unit test for the property 'Efficiency'
        }
        /// <summary>
        /// Test the property 'HourlyPay'
        /// </summary>
        [Test]
        public void HourlyPayTest()
        {
            // TODO unit test for the property 'HourlyPay'
        }
        /// <summary>
        /// Test the property 'LastRestDate'
        /// </summary>
        [Test]
        public void LastRestDateTest()
        {
            // TODO unit test for the property 'LastRestDate'
        }

    }

}
