/* 
 * Workforce Optimisation API
 *
 * Solver engine for solving workforce optimisation problems
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@solvice.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ErrorCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ErrorCodeTests
    {
        // TODO uncomment below to declare an instance variable for ErrorCode
        //private ErrorCode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ErrorCode
            //instance = new ErrorCode();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErrorCode
        /// </summary>
        [Test]
        public void ErrorCodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ErrorCode
            //Assert.IsInstanceOfType<ErrorCode> (instance, "variable 'instance' is a ErrorCode");
        }


        /// <summary>
        /// Test the property '_ErrorCode'
        /// </summary>
        [Test]
        public void _ErrorCodeTest()
        {
            // TODO unit test for the property '_ErrorCode'
        }
        /// <summary>
        /// Test the property 'Explanation'
        /// </summary>
        [Test]
        public void ExplanationTest()
        {
            // TODO unit test for the property 'Explanation'
        }
        /// <summary>
        /// Test the property 'Line'
        /// </summary>
        [Test]
        public void LineTest()
        {
            // TODO unit test for the property 'Line'
        }
        /// <summary>
        /// Test the property 'Column'
        /// </summary>
        [Test]
        public void ColumnTest()
        {
            // TODO unit test for the property 'Column'
        }

    }

}
