/* 
 * Workforce Optimisation API
 *
 * Solver engine for solving workforce optimisation problems
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@solvice.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ShiftRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShiftRequestTests
    {
        // TODO uncomment below to declare an instance variable for ShiftRequest
        //private ShiftRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShiftRequest
            //instance = new ShiftRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShiftRequest
        /// </summary>
        [Test]
        public void ShiftRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShiftRequest
            //Assert.IsInstanceOfType<ShiftRequest> (instance, "variable 'instance' is a ShiftRequest");
        }


        /// <summary>
        /// Test the property 'Demand'
        /// </summary>
        [Test]
        public void DemandTest()
        {
            // TODO unit test for the property 'Demand'
        }
        /// <summary>
        /// Test the property 'Employees'
        /// </summary>
        [Test]
        public void EmployeesTest()
        {
            // TODO unit test for the property 'Employees'
        }
        /// <summary>
        /// Test the property 'Statutes'
        /// </summary>
        [Test]
        public void StatutesTest()
        {
            // TODO unit test for the property 'Statutes'
        }

    }

}
