/* 
 * Workforce Optimisation API
 *
 * Solver engine for solving workforce optimisation problems
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@solvice.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ShiftSolution
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShiftSolutionTests
    {
        // TODO uncomment below to declare an instance variable for ShiftSolution
        //private ShiftSolution instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShiftSolution
            //instance = new ShiftSolution();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShiftSolution
        /// </summary>
        [Test]
        public void ShiftSolutionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShiftSolution
            //Assert.IsInstanceOfType<ShiftSolution> (instance, "variable 'instance' is a ShiftSolution");
        }


        /// <summary>
        /// Test the property 'Solution'
        /// </summary>
        [Test]
        public void SolutionTest()
        {
            // TODO unit test for the property 'Solution'
        }

    }

}
