/* 
 * Workforce Optimisation API
 *
 * Solver engine for solving workforce optimisation problems
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@solvice.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Statute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatuteTests
    {
        // TODO uncomment below to declare an instance variable for Statute
        //private Statute instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Statute
            //instance = new Statute();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Statute
        /// </summary>
        [Test]
        public void StatuteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Statute
            //Assert.IsInstanceOfType<Statute> (instance, "variable 'instance' is a Statute");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'MinShiftLength'
        /// </summary>
        [Test]
        public void MinShiftLengthTest()
        {
            // TODO unit test for the property 'MinShiftLength'
        }
        /// <summary>
        /// Test the property 'MaxShiftLength'
        /// </summary>
        [Test]
        public void MaxShiftLengthTest()
        {
            // TODO unit test for the property 'MaxShiftLength'
        }
        /// <summary>
        /// Test the property 'MinRestBetweenShifts'
        /// </summary>
        [Test]
        public void MinRestBetweenShiftsTest()
        {
            // TODO unit test for the property 'MinRestBetweenShifts'
        }
        /// <summary>
        /// Test the property 'MaxConsecutiveWorkDays'
        /// </summary>
        [Test]
        public void MaxConsecutiveWorkDaysTest()
        {
            // TODO unit test for the property 'MaxConsecutiveWorkDays'
        }
        /// <summary>
        /// Test the property 'MaxHrsPerWeek'
        /// </summary>
        [Test]
        public void MaxHrsPerWeekTest()
        {
            // TODO unit test for the property 'MaxHrsPerWeek'
        }
        /// <summary>
        /// Test the property 'MinHrsPerWeek'
        /// </summary>
        [Test]
        public void MinHrsPerWeekTest()
        {
            // TODO unit test for the property 'MinHrsPerWeek'
        }
        /// <summary>
        /// Test the property 'ShiftStart'
        /// </summary>
        [Test]
        public void ShiftStartTest()
        {
            // TODO unit test for the property 'ShiftStart'
        }
        /// <summary>
        /// Test the property 'LatestShiftStart'
        /// </summary>
        [Test]
        public void LatestShiftStartTest()
        {
            // TODO unit test for the property 'LatestShiftStart'
        }
        /// <summary>
        /// Test the property 'ShiftEnd'
        /// </summary>
        [Test]
        public void ShiftEndTest()
        {
            // TODO unit test for the property 'ShiftEnd'
        }
        /// <summary>
        /// Test the property 'MinHoursMonth'
        /// </summary>
        [Test]
        public void MinHoursMonthTest()
        {
            // TODO unit test for the property 'MinHoursMonth'
        }
        /// <summary>
        /// Test the property 'MaxHoursMonth'
        /// </summary>
        [Test]
        public void MaxHoursMonthTest()
        {
            // TODO unit test for the property 'MaxHoursMonth'
        }
        /// <summary>
        /// Test the property 'OverTimeThreshold1'
        /// </summary>
        [Test]
        public void OverTimeThreshold1Test()
        {
            // TODO unit test for the property 'OverTimeThreshold1'
        }
        /// <summary>
        /// Test the property 'OverTimeRaise1'
        /// </summary>
        [Test]
        public void OverTimeRaise1Test()
        {
            // TODO unit test for the property 'OverTimeRaise1'
        }
        /// <summary>
        /// Test the property 'OverTimeThreshold2'
        /// </summary>
        [Test]
        public void OverTimeThreshold2Test()
        {
            // TODO unit test for the property 'OverTimeThreshold2'
        }
        /// <summary>
        /// Test the property 'OverTimeRaise2'
        /// </summary>
        [Test]
        public void OverTimeRaise2Test()
        {
            // TODO unit test for the property 'OverTimeRaise2'
        }
        /// <summary>
        /// Test the property 'OverTimeWeeklyThreshold1'
        /// </summary>
        [Test]
        public void OverTimeWeeklyThreshold1Test()
        {
            // TODO unit test for the property 'OverTimeWeeklyThreshold1'
        }
        /// <summary>
        /// Test the property 'OverTimeWeeklyRaise1'
        /// </summary>
        [Test]
        public void OverTimeWeeklyRaise1Test()
        {
            // TODO unit test for the property 'OverTimeWeeklyRaise1'
        }
        /// <summary>
        /// Test the property 'NightlyThreshold1'
        /// </summary>
        [Test]
        public void NightlyThreshold1Test()
        {
            // TODO unit test for the property 'NightlyThreshold1'
        }
        /// <summary>
        /// Test the property 'NightlyRaise'
        /// </summary>
        [Test]
        public void NightlyRaiseTest()
        {
            // TODO unit test for the property 'NightlyRaise'
        }

    }

}
