# coding: utf-8

"""
    Workforce Optimisation API

    Solver engine for solving workforce optimisation problems  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@solvice.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.task_api import TaskApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = api.task_api.TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_solution(self):
        """Test case for get_solution

        Get a solution  # noqa: E501
        """
        pass

    def test_get_status(self):
        """Test case for get_status

        Get a status  # noqa: E501
        """
        pass

    def test_solve_task(self):
        """Test case for solve_task

        Solve TASK problem  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
