# coding: utf-8

"""
    Workforce Optimisation API

    Solver engine for solving workforce optimisation problems  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@solvice.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.error_code import ErrorCode  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorCode(unittest.TestCase):
    """ErrorCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorCode(self):
        """Test ErrorCode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_code.ErrorCode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
