# coding: utf-8

"""
    Workforce Optimisation API

    Solver engine for solving workforce optimisation problems  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@solvice.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.status_job import StatusJob  # noqa: E501
from swagger_client.rest import ApiException


class TestStatusJob(unittest.TestCase):
    """StatusJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusJob(self):
        """Test StatusJob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.status_job.StatusJob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
