<?php
/**
 * StatuteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Workforce Optimisation API
 *
 * Solver engine for solving workforce optimisation problems
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@solvice.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StatuteTest Class Doc Comment
 *
 * @category    Class
 * @description Statute
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StatuteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Statute"
     */
    public function testStatute()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "min_shift_length"
     */
    public function testPropertyMinShiftLength()
    {
    }

    /**
     * Test attribute "max_shift_length"
     */
    public function testPropertyMaxShiftLength()
    {
    }

    /**
     * Test attribute "min_rest_between_shifts"
     */
    public function testPropertyMinRestBetweenShifts()
    {
    }

    /**
     * Test attribute "max_consecutive_work_days"
     */
    public function testPropertyMaxConsecutiveWorkDays()
    {
    }

    /**
     * Test attribute "max_hrs_per_week"
     */
    public function testPropertyMaxHrsPerWeek()
    {
    }

    /**
     * Test attribute "min_hrs_per_week"
     */
    public function testPropertyMinHrsPerWeek()
    {
    }

    /**
     * Test attribute "shift_start"
     */
    public function testPropertyShiftStart()
    {
    }

    /**
     * Test attribute "latest_shift_start"
     */
    public function testPropertyLatestShiftStart()
    {
    }

    /**
     * Test attribute "shift_end"
     */
    public function testPropertyShiftEnd()
    {
    }

    /**
     * Test attribute "min_hours_month"
     */
    public function testPropertyMinHoursMonth()
    {
    }

    /**
     * Test attribute "max_hours_month"
     */
    public function testPropertyMaxHoursMonth()
    {
    }

    /**
     * Test attribute "over_time_threshold1"
     */
    public function testPropertyOverTimeThreshold1()
    {
    }

    /**
     * Test attribute "over_time_raise1"
     */
    public function testPropertyOverTimeRaise1()
    {
    }

    /**
     * Test attribute "over_time_threshold2"
     */
    public function testPropertyOverTimeThreshold2()
    {
    }

    /**
     * Test attribute "over_time_raise2"
     */
    public function testPropertyOverTimeRaise2()
    {
    }

    /**
     * Test attribute "over_time_weekly_threshold1"
     */
    public function testPropertyOverTimeWeeklyThreshold1()
    {
    }

    /**
     * Test attribute "over_time_weekly_raise1"
     */
    public function testPropertyOverTimeWeeklyRaise1()
    {
    }

    /**
     * Test attribute "nightly_threshold1"
     */
    public function testPropertyNightlyThreshold1()
    {
    }

    /**
     * Test attribute "nightly_raise"
     */
    public function testPropertyNightlyRaise()
    {
    }
}
